### ISSUE TITLE
Won't accept my credentials

### ISSUE THREAD

**Issue by djmtype** [msigwart/gatsby-source-google-calendar#5]
I've enabled my Google Calendar API following the setup instructions found on this plugin's Readme. I added the 2 variables (GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET) to my .env file which resides in the root, yet I'm still getting this after running `gatsby develop`.

```
"gatsby-source-google-calendar" threw an error while running the onCreateDevServer lifecycle:

    No client configuration available.
    Enable the Google Calendar API by visiting:

    https://developers.google.com/calendar/quickstart/nodejs#step_1_turn_on_the

    Follow the workflow and then store Client ID and Client Secret in your .env* files as
    GOOGLE_CLIENT_ID=<client_id>
    GOOGLE_CLIENT_SECRET=<client_secret>
```
![Screen Shot 12](https://user-images.githubusercontent.com/930713/103370723-882d7980-4a9b-11eb-8949-68b49303e8da.png)

**Comment by msigwart** [comment]
Hey, thank you for the issue! Were you able to solve the problem? 

Is your `.env` file called `.env.development`? When you run `gatsby develop`, Gatsby runs in the "development" environment. Accordingly, your `.env` file must be called `.env.development` so that your defined environment variables are loaded correctly.

By default, Gatsby supports [two environments](https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/), "development" and "production". When you run `gatsby build` or `gatsby serve`, Gatsby runs in the "production" environment. Accordingly, your `.env` file must be called `.env.production`.

Please let me know if you run into any more problems!

**Comment by djmtype** [comment]
@msigwart My bad. This is my very first attempt with Gatsby. I breezed through the docs. Lesson learned.

**Comment by natalyjazzviolin** [comment]
I'm getting a similar issue - the plugin does not work after it's successfully authorized. I'm placing all tokens (ID, SECRET, ACCESS, REFRESH) in both the .end.development and .env.production files.

This is the message I get:

```
File: node_modules/gatsby-source-google-calendar/gatsby-node.js:208:11

Error: invalid_grant
```

Is there a specific way I should be configuring the OAuth Consent Screen? I'd appreciate any advice!
